Pi:
  network:
    listening_ip: "0.0.0.0" #default
    server_ip: "your_server_addr"
    server_port: 5011
    receive_port: 5020
    sample_rate: 16000 #should not be touched
    channels: 1 #should not be touched
    chunk_size: 512
    output_volume: 0.3
    buffer_ms: 20 
    max_udp_packet: 1400
